[package]
name = "crawl_model"
version = "0.1.0"
authors = ["Richard McCormack <brick@brick.codes>"]

[dependencies]
diesel = { version = "0.99", features = ["sqlite", "large-tables"] }
dotenv = "0.10.1"
